services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Derhansen\SfYubikey\:
    resource: '../Classes/*'

  Derhansen\SfYubikey\Authentication\YubikeyAuthService:
    public: true
