name: Code Quality Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - { php: 8.1, coverage: 0}

    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2

      - name: Validate composer.json
        run: |
          cd .Build
          composer validate

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies
        run: |
          cd .Build
          composer install --no-progress

      - name: Validate PHP coding guidelines
        run: |
          .Build/vendor/bin/php-cs-fixer fix --config=.Build/php-cs-fixer/.php-cs-fixer.php -v --dry-run --stop-on-violation --using-cache=no

      - name: Run phpstan checks
        run: |
          .Build/vendor/bin/phpstan --configuration=.Build/phpstan/phpstan.neon